- name: Ensure Jenkins repo is installed.
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: Install jenkins
  yum:
    name:
      - jenkins
    state: present

# TODO: Edit /etc/sysconfig/jenkins

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=restarted enabled=yes
    